apiVersion: v3
kind: Service
metadata:
  labels:
    app: simple-nodejs-app
  name: simple-nodejs-app
spec:
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app: simple-nodejs-app
